# Generated by Django 2.1 on 2020-02-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partsnumber', '0003_partnumberclass'),
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsArrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('ro_number', models.CharField(max_length=50, verbose_name='Ro Number')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
                ('remarks', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('NOT COMPLETE', 'NOT COMPLETE'), ('LACKING', 'LACKING')], max_length=200, verbose_name='Remarks')),
                ('date_arrival', models.DateTimeField(verbose_name='Date Arrival')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.ServiceAdvisor', verbose_name='Service Advisor')),
                ('item_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsnumber.PartNumberClass', verbose_name='Item Class')),
                ('partnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsnumber.PartsNumber', verbose_name='Part Number')),
            ],
            options={
                'verbose_name': 'Parts Arrival',
                'verbose_name_plural': 'Parts Arrivals',
                'db_table': 'arrival',
                'ordering': ['id'],
            },
        ),
    ]
