# Generated by Django 2.2 on 2020-07-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsarrival',
            name='reason',
            field=models.CharField(max_length=200, verbose_name='Reasons'),
        ),
    ]
