# Generated by Django 2.2 on 2021-04-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsarrival',
            name='ro_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='RO/RE Number'),
        ),
    ]
