# Generated by Django 2.1 on 2020-02-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsarrival',
            name='description',
        ),
    ]
