# Generated by Django 2.1 on 2020-03-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0002_remove_partsarrival_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsarrival',
            name='date_arrival',
            field=models.CharField(max_length=20, verbose_name='Date Arrival'),
        ),
    ]
