# Generated by Django 2.2 on 2021-05-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0002_auto_20210429_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsarrival',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='partsarrival',
            name='date_arrival',
            field=models.DateField(verbose_name='Date Arrival'),
        ),
        migrations.AlterField(
            model_name='partsarrival',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
