# Generated by Django 2.2 on 2021-04-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceadvisor',
            name='first_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='First Name'),
        ),
    ]
