# Generated by Django 2.1 on 2020-08-13 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartNumberClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('class_name', models.CharField(max_length=20, verbose_name='Class name')),
                ('charge_type', models.CharField(max_length=20, verbose_name='Charge Type')),
                ('code_name', models.CharField(max_length=7, verbose_name='Code Name/Code Number')),
            ],
            options={
                'verbose_name': 'Part Number Class',
                'verbose_name_plural': 'Part Number Classes',
                'db_table': 'partnumber_class',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PartsNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('partnumber', models.CharField(max_length=200, verbose_name='Parts Number')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Part Number',
                'verbose_name_plural': 'Parts Number',
                'db_table': 'partnumbers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('um', models.CharField(max_length=20, verbose_name='Unit of Measure')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Unit of Measures',
                'db_table': 'um',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='partsnumber',
            name='unit_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsnumber.UnitMeasure', verbose_name='Unit of Measure'),
        ),
    ]
