# Generated by Django 2.1 on 2020-01-14 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartsNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "partnumber",
                    models.CharField(max_length=200, verbose_name="Parts Number"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=200, verbose_name="Part Number Description"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="UnitMeasure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("um", models.CharField(max_length=20, verbose_name="Unit of Measure")),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="partsnumber",
            name="unit_measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="partsnumber.UnitMeasure",
                verbose_name="Unit of Measure",
            ),
        ),
    ]
