# Generated by Django 2.2 on 2021-03-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsnumber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsnumber',
            name='partnumber',
            field=models.CharField(max_length=200, verbose_name='Parts Number'),
        ),
        migrations.AlterField(
            model_name='partsnumber',
            name='source_code',
            field=models.CharField(choices=[('01', 'Nissan Japan-01'), ('02', 'Nissan Taiwan-02'), ('05', 'Nissan Thailand-05'), ('08', 'Nissan Indonesia-08')], max_length=200, verbose_name='Source Code'),
        ),
    ]
