# Generated by Django 2.1 on 2020-03-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsnumber', '0003_partnumberclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnumberclass',
            name='code_name',
            field=models.CharField(max_length=7, verbose_name='Code Name/Code Number'),
        ),
    ]
